backend:
  name: github
  repo: oceanoweb/bicalho-website
  branch: master

publish_mode: editorial_workflow
media_folder: static/products-images
public_folder: ../products-images

collections:
  - name: 'products'
    label: 'products'
    folder: 'products'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Preço', name: 'price', widget: 'string' }
      - { label: 'Parcelamento', name: 'installments', widget: 'number', value_type: "int" }
      - { label: 'Preço parcelado', name: 'installmentsPrice', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'list' }
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: "Categoria", name: "category", widget: "list" }
      - { label: "Sub Categoria", name: "subcategory", widget: "list" }
      - { label: "Desconto", name: "discount", widget: "string", required: false }